// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitorLog.ApplicationDBContextService;

#nullable disable

namespace VisitorLog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitorLog.Models.LogModel", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("QRCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VisitorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId");

                    b.HasIndex("QRCodeId");

                    b.HasIndex("VisitorId");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("VisitorLog.Models.QRCodeModel", b =>
                {
                    b.Property<Guid>("QRCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCodeAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QRCodeId");

                    b.ToTable("qrcodes", (string)null);
                });

            modelBuilder.Entity("VisitorLog.Models.QRSetModel", b =>
                {
                    b.Property<Guid>("QRSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QRCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QRSetId");

                    b.HasIndex("QRCodeId");

                    b.HasIndex("VisitorId");

                    b.ToTable("qrsets", (string)null);
                });

            modelBuilder.Entity("VisitorLog.Models.VisitorModel", b =>
                {
                    b.Property<Guid>("VisitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Picture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PurposeOfVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorId");

                    b.ToTable("visitors", (string)null);
                });

            modelBuilder.Entity("VisitorLog.Models.LogModel", b =>
                {
                    b.HasOne("VisitorLog.Models.QRCodeModel", "QRCode")
                        .WithMany()
                        .HasForeignKey("QRCodeId");

                    b.HasOne("VisitorLog.Models.VisitorModel", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorId");

                    b.Navigation("QRCode");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("VisitorLog.Models.QRSetModel", b =>
                {
                    b.HasOne("VisitorLog.Models.QRCodeModel", "QRCode")
                        .WithMany()
                        .HasForeignKey("QRCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorLog.Models.VisitorModel", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QRCode");

                    b.Navigation("Visitor");
                });
#pragma warning restore 612, 618
        }
    }
}
